### ISSUE TITLE
Wrong info of "--verbose" in watch mode

### ISSUE THREAD

**Issue by chengzhang1016** [ingvagabund/cluster-capacity#17]
There are two problems in output of "--verbose" in watch mode:
1. Althrough I have created namespace "cluster-capacity", the output of "--verbose" in watch mode still give the error `Unable to create next pod to schedule: Pod's namespace cluster-capacity not found: Unable to create getter for namespaces: Requested namespaces resource cluster-capacity not found`.

2. I think we don't need let user know the detail info of "ReplicaSet", suggest remove `E1205 00:43:23.701296   18452 reflector.go:361] github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:481: expected type *extensions.ReplicaSet, but watch event object had type *v1beta1.ReplicaSet` in output of "--verbose". Because user always will not use `2>/dev/null` to filter errors.

```
# kc get namespace | grep cluster-capacity
cluster-capacity   Active    2h
```
```
# cc --podspec examples/pod.yaml --period 1 --verbose
Unable to create next pod to schedule: Pod's namespace cluster-capacity not found: Unable to create getter for namespaces: Requested namespaces resource cluster-capacity not found

E1205 00:43:23.701296   18452 reflector.go:361] github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:481: expected type *extensions.ReplicaSet, but watch event object had type *v1beta1.ReplicaSet
E1205 00:43:23.810525   18452 factory.go:583] Error scheduling cluster-capacity small-pod-16: pod (small-pod-16) failed to fit in any node
fit failure on node (ec2-54-158-106-111.compute-1.amazonaws.com): Insufficient cpu
fit failure on node (ec2-54-161-105-73.compute-1.amazonaws.com): Insufficient cpu
; retrying
Pod requirements:
	- CPU: 150m
	- Memory: 100Mi

The cluster can schedule 16 instance(s) of the pod.
Termination reason: FailedScheduling: pod (small-pod-16) failed to fit in any node
fit failure on node (ec2-54-158-106-111.compute-1.amazonaws.com): Insufficient cpu
fit failure on node (ec2-54-161-105-73.compute-1.amazonaws.com): Insufficient cpu

Pod distribution among nodes:
	- ec2-54-158-106-111.compute-1.amazonaws.com: 9 instance(s)
	- ec2-54-161-105-73.compute-1.amazonaws.com: 7 instance(s)
```

**Comment by ingvagabund** [comment]
Per 1) fixed with https://github.com/ingvagabund/cluster-capacity/commit/5eb5846369214821d63df333432d1a4a1d322d82. It takes some time before the framework sync with the cluster objects. Thus, the reason why the first run reports missing namespace.

Per 2) those are internal scheduler errors, nothing I can do about it.

**Comment by chengzhang1016** [comment]
Verified. Thanks.
